using /tmp/launcher.221971.hostlist.WKFOJzs5 to get hosts
starting job on compute-1-1-6
starting job on compute-1-1-16
starting job on compute-1-1-19
starting job on compute-1-1-20
starting job on compute-1-1-21
starting job on compute-1-1-23
starting job on compute-1-1-28
starting job on compute-1-1-34
starting job on compute-1-1-36
starting job on compute-1-1-37
starting job on compute-1-1-39
starting job on compute-1-1-40
starting job on compute-1-2-1
starting job on compute-1-2-15
starting job on compute-1-2-17
starting job on compute-1-2-25
starting job on compute-1-2-31
Warning: Permanently added 'compute-1-1-28,10.247.1.38' (ECDSA) to the list of known hosts.
starting job on compute-1-2-32
starting job on compute-1-3-24
starting job on compute-1-3-26
starting job on compute-1-3-34
starting job on compute-1-3-39
starting job on compute-1-3-40
starting job on compute-1-4-6
starting job on compute-1-4-7
starting job on compute-1-4-8
starting job on compute-1-4-9
starting job on compute-1-4-10
starting job on compute-1-4-20
starting job on compute-1-4-21
starting job on compute-1-4-22
starting job on compute-1-4-25
starting job on compute-1-4-35
starting job on compute-1-4-36
starting job on compute-1-4-37
starting job on compute-1-4-38
starting job on compute-1-4-39
starting job on compute-1-4-40
starting job on compute-1-6-8
starting job on compute-1-6-9
starting job on compute-1-6-10
Warning: Permanently added 'compute-1-4-20,10.247.1.150' (ECDSA) to the list of known hosts.
starting job on compute-1-6-13
starting job on compute-1-6-14
starting job on compute-1-6-20
Warning: Permanently added 'compute-1-4-35,10.247.1.165' (ECDSA) to the list of known hosts.
starting job on compute-1-6-22
starting job on compute-1-6-23
Warning: Permanently added 'compute-1-6-8,10.247.1.218' (ECDSA) to the list of known hosts.
starting job on compute-1-6-24
starting job on compute-1-6-26
starting job on compute-1-6-29
starting job on compute-1-6-36
starting job on compute-1-6-37
starting job on compute-1-6-38
starting job on compute-1-6-39
starting job on compute-1-7-1
Warning: Permanently added 'compute-1-6-20,10.247.1.230' (ECDSA) to the list of known hosts.
starting job on compute-1-7-10
starting job on compute-1-7-14
starting job on compute-1-7-16
starting job on compute-1-7-17
starting job on compute-1-7-24
Warning: Permanently added 'compute-1-6-36,10.247.1.246' (ECDSA) to the list of known hosts.
starting job on compute-1-7-25
starting job on compute-1-7-26
starting job on compute-1-7-32
starting job on compute-1-7-33
starting job on compute-2-1-10
starting job on compute-2-1-11
starting job on compute-2-1-12
starting job on compute-2-1-13
starting job on compute-2-1-14
starting job on compute-2-1-21
starting job on compute-2-1-22
Warning: Permanently added 'compute-1-7-24,10.247.2.34' (ECDSA) to the list of known hosts.
starting job on compute-2-1-24
starting job on compute-2-1-25
starting job on compute-2-1-26
Warning: Permanently added 'compute-1-7-16,10.247.2.26' (ECDSA) to the list of known hosts.
Warning: Permanently added 'compute-2-1-10,10.247.2.180' (ECDSA) to the list of known hosts.
Warning: Permanently added 'compute-1-7-26,10.247.2.36' (ECDSA) to the list of known hosts.
Warning: Permanently added 'compute-2-1-21,10.247.2.191' (ECDSA) to the list of known hosts.
Warning: Permanently added 'compute-1-7-32,10.247.2.42' (ECDSA) to the list of known hosts.
starting job on compute-2-1-31
Warning: Permanently added 'compute-2-1-31,10.247.2.201' (ECDSA) to the list of known hosts.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/tvb/datatypes/surfaces.py:63: UserWarning: Geodesic distance module is unavailable; some functionality for surfaces will be unavailable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sim2hdf5.py", line 52, in <module>
    df.to_hdf(save_path, key='raw', mode='w')
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/core/generic.py", line 2775, in to_hdf
    pytables.to_hdf(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 311, in to_hdf
    with HDFStore(
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/io/pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "/home/nkk170000/.conda/envs/tvbenv/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
